### ISSUE TITLE
playwright

### ISSUE THREAD

**Issue by sbb-python** [OlivierWinsemius/playcumber#1]

**Comment by sandip-bhosale** [comment]
hello i like the way you have implemented playwright cucumber but it would be helpful you could provide some descriptive information about each file... if you can make some youtube video about implementation that would be really great

**Comment by sandip-bhosale** [comment]
This is regarding your implementation on playwright cucumber. I really wanted learn and implement this framework, the way you have implemented cucumber playwright. To understand more about each file and code, is it possible to provide descriptive information? or any youtube video or any other source or course available ?


https://github.com/OlivierWinsemius/playcumber/tree/main

please help
